### ISSUE TITLE
In electron on windows, copy the vbs file in the resources

### ISSUE THREAD

**Issue by TranceGeniK** [nwutils/create-desktop-shortcuts#1]
Just a tip here for those using electron/electron-builder, be sure to copy the vbs file in the resources/app directory

```
"extraResources": [
            {
              "from": "node_modules/create-desktop-shortcuts/windows.vbs",
              "to": "app"
            }
          ],
```

**Comment by danperks** [comment]
This proves to be an issue when using [PKG](https://www.npmjs.com/package/pkg), but there is no option for "extra resources" available here so #53 could be a worthwhile pull to include. 

At the moment, I'm attempting to copy that `windows.vbs` script into the directory PKG unpacks to when it's run (usually `C:/snapshot/index.js` or something like that), but I'm not sure if that will work right now.
