### ISSUE TITLE
CWD on shortcuts

### ISSUE THREAD

**Issue by Tixxxon** [nwutils/create-desktop-shortcuts#21]
Hello! Why is it not possible to set the working directory in shortcuts? I looked in the code, it just sets an empty line, although changing to options.cwd everything works fine!
Thanks

**Comment by TheJaredWilcurt** [comment]
oh I guess I just forgot to set that up. Good catch.

**Comment by TheJaredWilcurt** [comment]
@Tixxxon This feature has been added and released in version 1.2.0.

:sheep: :it: :rocket: :shipit: :tada:
