### ISSUE TITLE
Add support for Windows Start menu

### ISSUE THREAD

**Issue by fp07** [nwutils/create-desktop-shortcuts#24]
Can we add support for the Windows Start menu?

> %ProgramData%\Microsoft\Windows\Start Menu\Programs
> %AppData%\Microsoft\Windows\Start Menu\Programs

**Comment by TheJaredWilcurt** [comment]
Assuming the script is running with proper permissions, that should already work. It is designed to handle `%whatever%`.

```js
const createDesktopShortcut = require('create-desktop-shortcuts');
const filePath = 'C:\\path\\to\\executable.exe';
const programData = createDesktopShortcut({
  windows: {
    filePath,
    outputPath: '%ProgramData%\Microsoft\Windows\Start Menu\Programs',
  }
});
const appData = createDesktopShortcut({
  windows: {
    filePath,
    outputPath: '%AppData%\Microsoft\Windows\Start Menu\Programs',
  }
});
if (!appData && !programData) {
  console.log('Could not create start menu shortcut');
}
```

**Comment by TheJaredWilcurt** [comment]
Actually, can you give me more information on which paths work on which OS, and the different paths for current user and "All Users".

I'm thinking the API could be updated to allow passing in `outputPath: 'Start Menu - All Users'` or `'Start Menu - Current User'`. And then we could check which version of windows is running, and use the correct path. But I need to know what the path is for each version of Windows and for All and Current.

**Comment by fp07** [comment]
Thanks for your response.

**Windows**
Here is the location for the global users:
C:\ProgramData\Microsoft\Windows\Start Menu

Global: %ProgramData%\Microsoft\Windows\Start Menu\Programs\
User: %AppData%\Microsoft\Windows\Start Menu\Programs\

Source: https://www.howtogeek.com/howto/6463/stupid-geek-tricks-how-to-open-the-start-menu-folder-in-windows-7/

**MacOS**
No information found atm.

**Linux**
/usr/local/share/applications; /usr/share/applications

@TheJaredWilcurt

**Comment by TheJaredWilcurt** [comment]
OS | Type | Path | Note
:-- | :-- | :-- | :--
Win 7+ | All Users | `%AllUsersProfile%\Microsoft\Start Menu\Programs` | `C:\ProgramData\Microsoft\Start Menu\Programs` But the `Start Menu` folder may not exist.
Win 7+ | All Users | `%ProgramData%\Microsoft\Windows\Start Menu\Programs` | Should be exactly same as above
Win 7+ | Current User | `%AppData%\Microsoft\Windows\Start Menu\Programs` | Should work fine\reliably
Linux | All Users | `/usr/share/applications` | According to Arch and Gnome
Linux | All Users | `/usr/local/share/applications/` | According to Arch
Linux | Current User | `~/.local/share/applications` | According to Gnome docs

OSX doesn't have a "Start menu" nor an official means of [adding items to the dock](https://developer.apple.com/forums/thread/122743)

In Windows 8+ it might be possible to pin a "tile" in the start menu, but that looks difficult, and out of scope for this library.

**Comment by fp07** [comment]
Thanks for your message @TheJaredWilcurt, I think we can add above to the README as extra?

**Comment by TheJaredWilcurt** [comment]
@fp07 This was added to the `README.md` and a new release includes it. `v1.2.1`
