### ISSUE TITLE
Does this support Windows XP?

### ISSUE THREAD

**Issue by shun634501730** [nwutils/create-desktop-shortcuts#26]
Hi author,

You know the NWJS support the Windows XP, so does this support Windows XP also?

I read the doc, but it seems only support Windows 7+?

**Comment by TheJaredWilcurt** [comment]
It *should* but I haven't tested it. If anything I'd think the bottleneck would be Node version. But I've tried to write it in a away that doesn't use much "modern" JS to make it as portable as possible.

**Comment by TheJaredWilcurt** [comment]
Just tested it and there's a few minor things that need to be tweaked for older versions of Node. I'll do a new release soon with those.

**Comment by TheJaredWilcurt** [comment]
Just did a new release. It runs on Windows XP just fine. It work with Node 4+. Added in some notes in the `README` about it.
