### ISSUE TITLE
support arguments on linux

### ISSUE THREAD

**Issue by unmellow** [nwutils/create-desktop-shortcuts#30]
[agregore-browser](https://github.com/AgregoreWeb/agregore-browser) uses this library to create bookmarks we did this using this code 
```js
      const shortcut = {
        filePath: appPath,
        outputPath: outputPath,
        name: shortcutName,
        comment: `Agregore Browser - ${url}`,
        arguments: url
      }

      const createShortcut = icon => {
        if (icon) shortcut.icon = icon
        // TODO: Kyran: Use Agregore icon if no icon provided.
        // TODO: Kyran: OSX doesn't have arguments option. See https://github.com/RangerMauve/agregore-browser/pull/53#issuecomment-705654060 for solution.
        createDesktopShortcut({
          windows: shortcut,
          linux: shortcut   
      }
```
file: https://github.com/AgregoreWeb/agregore-browser/blob/master/app/actions.js#L193

in hopes of generating a file something like this
```ini
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Exec=/usr/lib/agregore-browser/agregore-browser https://github.com/AgregoreWeb/agregore-browser/tree/master/docs
Name=agregore-browser docs at master · AgregoreWeb agregore-browser · GitHub
comment=Agregore Browser - https://github.com/AgregoreWeb/agregore-browser/tree/master/docs
Icon=/home/meltonmb/.config/agregore-browser/PWAs/agregore-browser docs at master · AgregoreWeb agregore-browser · GitHub/favicon.png
```

instead what we get is a file like this
```ini
#!/user/bin/env xdg-open
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Exec=/usr/lib/agregore-browser/agregore-browser
Name=Agregore Browser - https://github.com/AgregoreWeb/agregore-browser/tree/master/docs
comment=Agregore Browser - https://github.com/AgregoreWeb/agregore-browser/tree/master/docs
Icon=/home/meltonmb/.config/agregore-browser/PWAs/agregore-browser docs at master · AgregoreWeb agregore-browser · GitHub/favicon.png
```

issue being the latter doesn't open to the bookmarked page

is their any reason you don't support arguments on linux?
and would changing[ this line ](https://github.com/nwutils/create-desktop-shortcuts/blob/06ac283ecac39e41c5245c446086dd1754deb29e/src/library.js#L35) to
```js
let exec = 'Exec=' + options.linux.filePath + ' ' + options.linux.arguments;
```
be the correct way to patch this?

**Comment by TheJaredWilcurt** [comment]
Each OS has its own specific fields you can set for creating a shortcut. Windows happens to explicitly set the value of an `arguments` field:

* https://github.com/nwutils/create-desktop-shortcuts/blob/main/src/windows.vbs#L24

Though this is something I could arbitrarily add to OSX and Linux, we would lose accuracy with the specification for that OS's shortcuts. If an "arguments" feature is later added to these environments as their own specific field, they may have certain rules in place unique to that platform and that field (I can't predict the future). This would introduce confusion and breaking changes to the library in that future scenario.

As it is right now, I'd rather this library try to maintain it's accuracy to the OS's as best as possible.

In your example though, you could change it to something like this:

```js
const createShortcut = function (icon) {
  const windows = {
    filePath: appPath,
    outputPath,
    name: shortcutName,
    comment: 'Agregore Browser - ' + url,
    arguments: url,
    // TODO: Kyran: Use Agregore icon if no icon provided.
    icon
  };
  const linux = {
    ...windows,
    description: 'Agregore Browser - ' + url,
    filePath: appPath + ' ' + url
  };
  const osx = linux;

  createDesktopShortcut({ windows, linux, osx });
};
```

**Comment by unmellow** [comment]
> Each OS has its own specific fields you can set for creating a shortcut. Windows happens to explicitly set the value of an `arguments` field:
> 
>     * https://github.com/nwutils/create-desktop-shortcuts/blob/main/src/windows.vbs#L24
> 
> 
> Though this is something I could arbitrarily add to OSX and Linux, we would lose accuracy with the specification for that OS's shortcuts. If an "arguments" feature is later added to these environments as their own specific field, they may have certain rules in place unique to that platform and that field (I can't predict the future). This would introduce confusion and breaking changes to the library in that future scenario.
> 
> As it is right now, I'd rather this library try to maintain it's accuracy to the OS's as best as possible.
> 
> In your example though, you could change it to something like this:
> 
> ```js
> const createShortcut = function (icon) {
>   const windows = {
>     filePath: appPath,
>     outputPath,
>     name: shortcutName,
>     comment: 'Agregore Browser - ' + url,
>     arguments: url,
>     // TODO: Kyran: Use Agregore icon if no icon provided.
>     icon
>   };
>   const linux = {
>     ...windows,
>     description: 'Agregore Browser - ' + url,
>     filePath: appPath + ' ' + url
>   };
>   const osx = linux;
> 
>   createDesktopShortcut({ windows, linux, osx });
> };
> ```

using this code gives me this error whenever i try to create a bookmark
```js
Create-Desktop-Shortcuts:
LINUX filePath (with type of "Application") must exist and cannot be a folder: /home/meltonmb/src/agregore-browser/release/linux-unpacked/agregore-browser hyper://94f0cab7f60fcc2a711df11c85db5e0594d11e8a3efd04a06f46a3c34d03c418/ undefined
```
would it be possible to have an "other" type so we can put whatever we want here?

**Comment by TheJaredWilcurt** [comment]
This is actually a good point. I didn't think about how the validation would handle that. I think you've convinced me in this case to add the `arguments` into OSX and Linux also, like you originally suggested. I'd rather the validation be reliable and always on. If the OS's ever add their own `arguments` field, we'll deal with that when it happens I guess. It's unlikely that it would be very different than just passing them in by hand.

**Comment by TheJaredWilcurt** [comment]
This will be in v1.4.0 when released.
