### ISSUE TITLE
can't display the file poster

### ISSUE THREAD

**Issue by zxcvpn011** [nwutils/create-desktop-shortcuts#36]
- i was trying this module it's easy and works fine but it's not display the file poster like if i want to create a shortcut of a png which appears like this 
![123223](https://user-images.githubusercontent.com/78762579/117347415-614bdd80-aea9-11eb-8d47-cf27956b77e2.PNG)
- it's will be like this
![4641](https://user-images.githubusercontent.com/78762579/117347430-67da5500-aea9-11eb-91a2-f31cfec4728f.PNG)
- when i create it normally by the mouse the poster appears normally so what should i do to make it display as it's should to be

**Comment by TheJaredWilcurt** [comment]
Tested on windows 7 and it worked fine using this code:
```js
const createDesktopShortcut = require('create-desktop-shortcuts');
const shortcutsCreated = createDesktopShortcut({
  windows: { filePath: 'C:\\Users\\Owner\\Pictures\\nwjs.png' }
});
```
Could not reproduce.

**Comment by zxcvpn011** [comment]
- that was happend because i wrote the file path like that ```E:/Capture.PNG``` but when i write it like you ```E:\\Capture.PNG``` it's working thanks
