### ISSUE TITLE
Command is not supported

### ISSUE THREAD

**Issue by andy-chili-wang** [nwutils/create-desktop-shortcuts#39]
filePath can only accept a physical file, but command is not supported like "node my-product-script.js"

**Comment by TheJaredWilcurt** [comment]
Technically `node` isn't a command, it's a PATH variable that likely points to `C:\Program Files\nodejs\node.exe` or something similar.

We'd probably need to pull in `require('hasbin').sync('node')` or something like that to verify the item exists. Actually after looking at the [hasBin source](https://github.com/springernature/hasbin/blob/master/lib/hasbin.js), I think wouldn't be that hard to do this manually in the project. Keeping the dependencies at zero, and lowering the amount of code to just the parts needed for this task. Though if this library ever adds "async" functionality, it would be better to just pull in `hasbin` and `async` as deps.

**Comment by sysrage** [comment]
If I'm reading the original comment correctly, @andy-chili-wang is asking for `filePath` to accept arguments. However, the `arguments` property is already available.

```js
createDesktopShortcut({
  windows: {
    filePath: 'C:\\path\\to\\node.exe',
    arguments: 'C:\\path\\to\\my-product-script.js''
  }
});
```

**Comment by TheJaredWilcurt** [comment]
The question is about accessing `node` via PATH.

If you did 
```js
createDesktopShortcut({ windows: { filePath: 'node' } });
```
It would not pass the built in API validation, returning this error:
```
WINDOWS filePath does not exist: node
```
You could just pass in the hard coded file path to it, but Node in particular can live in many places on a computer. So if you are using this library to add a shortcut on someone else's machine, then just pointing to `node` is much more convenient than having to find the actual path to the executable on each computer.

We already go out of our way to handle `%USER%` and other environment variables. I don't see this as out of scope for the library.

Also, on second look, `hasBin` only returns a boolean if it exists, not the location of where it exists. So we'll need to do this logic here anyway.

**Comment by sysrage** [comment]
I agree that it could be handy to automatically search the user's path for an executable which matches the provided name. While I understand the desire to limit dependencies, the [which](https://www.npmjs.com/package/which) module can likely make this extremely easy.

**Comment by TheJaredWilcurt** [comment]
yeah, I might use that, total dependency chain then would be

* **create-desktop-shortcuts** - pretty small
  * **which** - pretty small
    * **isexe** - very small

The project would still be tiny, but not as easy to communicate that as just being able to say "ZERO DEPENDENCIES" in bold at the top of the readme.
