### ISSUE TITLE
Does this work to create .lnk files for folders? (like symlinks)

### ISSUE THREAD

**Issue by diavrank** [nwutils/create-desktop-shortcuts#49]
Hi, I was wondering if this package is able to create windows shortcuts but for folders. I need to create .lnk files from mac/linux system with nodejs.

**Comment by TheJaredWilcurt** [comment]
It has full support for everything you can do with shortcuts on any platform. However, to create a shortcut on Windows you need to spawn a child process for `wscript.exe` and pass in arguments (either the defaults or what you set via the JS API) as strings into a VBS file.

* [makeWindowsShortcut: function () {](https://github.com/nwutils/create-desktop-shortcuts/blob/785452671fcf9e7ee4a23bf66ddbe1c51bc80826/src/library.js#L139)
* [windows.vbs](https://github.com/nwutils/create-desktop-shortcuts/blob/main/src/windows.vbs)

So I would not expect it to be possible to create a windows shortcut from a non-windows machine. It works similarly for OSX, it runs the built in `ln` executable on the OS. On Linux it just makes a text file, but it also runs `chmod` command on it.

**Comment by diavrank** [comment]
Thanks for the information. I used bat files to solve my problem.
