### ISSUE TITLE
Default desktop folder doesn't exist when using OneDrive sync.

### ISSUE THREAD

**Issue by StoneyEagle** [nwutils/create-desktop-shortcuts#50]
I am synchronizing my user profile folders with OneDrive.
This results in the default %USERPROFILE%\Desktop folder not existing anymore.
OneDrive also changes the English name of the desktop folder to the localized name, in my case in dutch to Bureaublad.
%OneDrive% doesn't work in the shell. 

What I needed was:
```js
windows: {
    outputPath: execSync('[Environment]::GetFolderPath("Desktop")', {'shell':'powershell.exe'}).toString().trim(),
}
```

Maybe you can change the default to something like this since this is the way that works universally.
Source: https://stackoverflow.com/a/31747246/9242840 & https://stackoverflow.com/a/61219838/9242840

**Comment by TheJaredWilcurt** [comment]
Closing issue. This is released in version `1.6.0`.
