### ISSUE TITLE
Internet Shortcuts

### ISSUE THREAD

**Issue by uSkizzik** [nwutils/create-desktop-shortcuts#56]
Hi! So, I was wondering, is it possible to create internet shortcuts (.url files) using this?  
I saw this mentioned in the README but I'm getting an error.
Here's what I have:
```js
createDesktopShortcut({
   windows: {
      filePath: "skizzium://launch/" + game
   }
})
```
That just errors out with: 
```
No shortcuts were created due to lack of accurate details passed in to options object { verbose: true, onlyCurrentOS: true }
```

**Comment by TheJaredWilcurt** [comment]
It does not handle what you want (custom URL protocols). However, the `.url` format is just plain text, making it relatively trivial in comparison to handle on your own.

```js
// Import some modules that come built in to Node
const fs = require('fs');
const os = require('os');
const path = require('path');

function createDesktopLink (game) {
  // Check if you are not on Windows
  if (os.platform() !== 'win32') {
    // function ends here, because you aren't on windows
    return;
  }
  // CRLF is the line endings used in native windows files
  const CRLF = '\r\n';

  // The location of where to put the file, this will default to the desktop of the current user
  const file = path.join(os.homedir(), 'Desktop', game + '.url');
  // The content of the file, each item in the array is a new line in the file
  const data = [
    '[InternetShortcut]',
    'URL=skizzium://launch/' + game
  ].join(CRLF) + CRLF;

  // only save the file if it doesn't already exist
  if (!fs.existsSync(file)) {
    // Save the file
    fs.writeFileSync(file, data);
  }
}

createDesktopLink('Project-Apple');
```

If you want to add a custom icon or anything, checkout this guide:

* http://www.lyberty.com/encyc/articles/tech/dot_url_format_-_an_unofficial_guide.html

**Comment by uSkizzik** [comment]
> It does not handle what you want (custom URL protocols). However, the `.url` format is just plain text, making it relatively trivial in comparison to handle on your own.
> 
> ```js
> // Import some modules that come built in to Node
> const fs = require('fs');
> const os = require('os');
> const path = require('path');
> 
> function createDesktopLink (game) {
>   // Check if you are not on Windows
>   if (os.platform() !== 'win32') {
>     // function ends here, because you aren't on windows
>     return;
>   }
>   // CRLF is the line endings used in native windows files
>   const CRLF = '\r\n';
> 
>   // The location of where to put the file (the desktop of the current user)
>   const file = path.join(os.homedir(), 'Desktop', game + '.url');
>   // The content of the file, each item in the array is a new line in the file
>   const data = [
>     '[InternetShortcut]',
>     'URL=skizzium://launch/' + game
>   ].join(CRLF) + CRLF;
> 
>   // only save the file if it doesn't already exist
>   if (!fs.existsSync(file)) {
>     // Save the file
>     fs.writeFileSync(file, data);
>   }
> }
> 
> createDesktopLink('Project-Apple');
> ```
> 
> If you want to add a custom icon or anything, checkout this guide:
> 
> * http://www.lyberty.com/encyc/articles/tech/dot_url_format_-_an_unofficial_guide.html

Hate it when something doesn't support deeplinks which is often the case.  
Anyways, thanks for the help!

**Comment by uSkizzik** [comment]
> `const file = path.join(os.homedir(), 'Desktop', game + '.url');` That will work for most people, however if you are using a OneDrive account for example, then your desktop or profile may be in a weird place.
> 
> You can `npm install --save which` and do:
> 
> ```js
> const which = require('which');
> const exec = require('child_process').execSync;
> 
> function getDesktopLocation () {
>   let desktop;
>   if (process.platform === 'win32') {
>     const powershellExists = which.sync('powershell.exe', { nothrow: true });
>      if (powershellExists) {
>       desktop = exec('[Environment]::GetFolderPath("Desktop")', { shell: 'powershell.exe' }) || '';
>       desktop = desktop.toString().trim();
>     }
>   }
>   desktop = desktop || path.join(os.homedir(), 'Desktop');
>   return desktop;
> }
> ```
> 
> That will find the _real_ location using powershell, or if powershell isn't present, assume it is in the normal location.

Actually, I forgot I can just use Electron's getPath function to get some standard paths such as the Desktop. I tried it and it did the job. Thanks for the reply though!
