### ISSUE TITLE
filePath with spaces + arguments problem

### ISSUE THREAD

**Issue by ninopetrovic** [nwutils/create-desktop-shortcuts#57]
Creating shortcut where filePath contains spaces (eg.: '/foo/foo foo/foo.exe') and arguments are also set... leads to an issue where the created shortcut lists target as: **/foo/foo foo/foo.exe -arguments** instead of **"/foo/foo foo/foo.exe" -arguments** (note the quotation marks)

**Comment by TheJaredWilcurt** [comment]
Is this on Windows (use of `.exe`)?

Can you put a min-repro code example

**Comment by TheJaredWilcurt** [comment]
Marked as "potential bug", waitig on details from @ninopetrovic
