### ISSUE TITLE
add exec option for linux

### ISSUE THREAD

**Issue by eye-wave** [nwutils/create-desktop-shortcuts#84]
Exec is on linux is not just `filePath`, you can execute commands with it.
When i try to make a Application shortcut for a shell script i get this error

```
_________________________
Create-Desktop-Shortcuts:
LINUX filePath (with type of "Application") must exist and cannot be a folder: /bin/bash -c ...
_________________________
```

**Comment by TheJaredWilcurt** [comment]
Show code.

**Comment by TheJaredWilcurt** [comment]
That message you are getting only occurs if:

* The value `'/bin/bash'` is not a string (it is)
* It does not exist (it does)
* If it is a directory (it isn't)

![cannot-reproduce](https://github.com/nwutils/create-desktop-shortcuts/assets/4629794/40a3ff3f-b337-4718-9abe-1a9c32d44698)

My assumption is you are doing this:

```js
createDesktopShortcuts({
  linux: {
    filePath: '/bin/bash -c'
  }
});
```

and you should be doing this instead:

```js
createDesktopShortcuts({
  linux: {
    filePath: '/bin/bash',
    arguments: '-c'
  }
});
```

**Comment by TheJaredWilcurt** [comment]
If this does not solve your issue, reopen this with code.
