### ISSUE TITLE
Expanding `%LOCALAPPDATA%` on windows makes the shortcut unshareable

### ISSUE THREAD

**Issue by johnnyd710** [nwutils/create-desktop-shortcuts#85]
I have a use case for creating a shortcut and then sharing the shortcut with others. The shortcut's `filePath` is an .exe located in the user's `%LOCALAPPDATA%` directory. This package will expand `%LOCALAPPDATA%` to `C:\Users\User.Name\AppDataLocal` during the validation process, which obviously won't work if I share with another user.

Shortcuts work with environment variables, so why remove them?

**Comment by TheJaredWilcurt** [comment]
Can you explain your use case further?

**Comment by johnnyd710** [comment]
> Can you explain your use case further?

I want to be able to create shortcuts on one machine and send it to another machine with a different username. To do this I need to create a shortcut using windows environmental variables instead of an absolute path

**Comment by TheJaredWilcurt** [comment]
This change has been merged and is in the newest release (v1.11.0).
